### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by epidrome** [ioniodi/study-guide#11]
Για κάθε ενότητα και σετ αρχείων που θέλετε να στείλετε θα πρέπει πρώτα να δημιουργείτε ένα νέο θέμα συζήτησης με τον αντίστοιχο τίτλο και αφού γίνει δεκτό ή/και γίνουν αλλαγές τότε μπορείτε να στέλνετε ένα αίτημα ενσωμάτωσης με αναφορά στο αντίστοιχο θέμα

Μερικά από παρακάτω δύσκολα ζητούμενα απαιτούν την δημιουργία νέων θεμάτων συζήτησης στο αποθετήριο του κώδικα έτσι ώστε να γίνουν περισσότερο εστιασμένα

Η προθεσμία τα εύκολα είναι το 1ο παραδοτέο και για τα δύσκολα το 2ο.

# Πολύ εύκολα
- [ ] [Εγκατάσταση εργαλείων τοπικά](https://github.com/ioniodi/study-guide/blob/master/README.md) και δημιουργία δοκιμαστικού PDF με ενδεικτικό περιεχόμενο από τον οδηγό σπουδών, χωρίς αίτημα ενσωμάτωσης στο κεντρικό αλλά με ανέβασμα του δοκιμαστικού στο δικό σας αποθετήριο. Εαν αυτό το βήμα δουλέψει σωστά τότε θα μπορείτε να φτιάξετε αυτόματα έναν οδηγό σπουδών στον φάκελο legacy/odt1718 με την εκτέλεση του σκριπτ .sh (ή με μια εντολή pandoc-latex) ο οποίος όμως δεν έχει άριστη εμφάνιση καθώς δημιουργήθηκε από απλές μετατροπές αρχείων, για αυτό θα προσπαθήσουμε να δημιουργήσουμε μια καλύτερη ροή εργασίας παρακάτω:
- [ ] Δηλώστε τα αρχεία που θα προσθέσετε σε ένα νέο θέμα ελέγχοντας πρώτα αν κάποιος άλλος έχει επιλέξει τα ίδια αρχεία κοιτάζοντας τα [ανοικτά](https://github.com/ioniodi/study-guide/issues) και [κλειστά](https://github.com/ioniodi/study-guide/issues?q=is%3Aissue+is%3Aclosed) θέμα που ήδη υπάρχουν. Η τελική δήλωση θα πρέπει να περιλαμβάνει: 10 αρχεία για τα οποία θα πρέπει να δημιουργήσετε το αντίστοιχο όνομα αρχείου, με ενδεικτικό περιεχόμενο αρχικά που μπορείτε να αντιγράψετε από την [τρέχουσα έκδοση του οδηγού σπουδών](https://github.com/ioniodi/study-guide/blob/master/legacy/odt1718/SG1718.md). Τα αρχεία αυτά **δεν** θα πρέπει να περιέχουν περιεχόμενο (π.χ., μαθήματα, καθηγητές, εργαστήρια, προγράμματα) που βρίσκεται ήδη [στην νέα ιστοσελίδα](https://github.com/ioniodi/site-gr). Ο τίτλος και το περιεχόμενο του κάθε αρχείου θα πρέπει να αναφέρονται σε μια μικρή και διακριτή υπο-ενότητα του οδηγού σπουδών (κάπου 300-500 λέξεις για κάθε αρχείο) . Για την επιτυχή δήλωση αρκεί να στείλετε τον τίτλο του αρχείου με ενδεικτικό περιεχόμενο (σε ενότητες και υπό-ενότητες), αλλά θα πρέπει πρώτα να γίνει αποδεκτή με νέο θέμα συζήτησης πριν γίνει αίτημα ενσωμάτωσης (pull request) που κάνατε έτσι ώστε να αποφύγουμε επικαλύψεις. Στο αίτημα ενσωμάτωσης θα πρέπει να κάνετε αναφορά στο αντίστοιχο θέμα (https://help.github.com/en/articles/closing-issues-using-keywords) έτσι ώστε με την αποδοχή του αιτήματος να κλείνει αυτόματα και το αντίστοιχο θέμα.
- [ ] Πρόσθετη επεξεργασία των αρχείων (π.χ., ομοιομορφία στις ενότητες-υποενότητες, πλήρες μορφοποιημένο περιεχόμενο, εικόνες, κτλ) και αίτημα ενσωμάτωσης
- [ ] Δημιουργία ενός τουλάχιστον μορφότυπου μετατροπής των αρχείων τύπου md (yaml front matter) από την [νέα ιστοσελίδα](https://github.com/ioniodi/site-gr) σε απλά αρχεία md. Για παράδειγμα υπάρχει ήδη στον φάκελο _templates το προσχέδιο για ένα μορφότυπο μετατροπής των αρχείων μαθημάτων  το οποίο βασίζεται σε τεχνική που παρουσιάζεται: https://github.com/mrzool/cv-boilerplate
- [ ] Ενδιάμεση αναφορά σύμφωνα με τις οδηγίες στο κεντρικό αποθετήριο εργασιών η οποία περιέχει ενδεικτικές οθόνες από την τοπική εγκατάσταση και λινκ προς το δοκιμαστικό PDF

## Εύκολα
- [ ] Εναλλακτικά στυλ (CSS ή/και .sty) για καλύτερη και συνεπή εμφάνιση σε ιστοσελίδα και εκτύπωση
- [ ] Συντονισμός με την ιστοσελίδα ώστε να έχουμε μόνο μια μορφή-θέση αρχείου για κάθε επιμέρους πληροφορία και δημιουργία μορφότυπου για την αυτόματη κατασκευή συγκεντρωτικών πινάκων, π.χ., για τα μαθήματα κάθε εξαμήνου.

## Δύσκολα
- [ ] Προγραμματιστική δημιουργία πινάκων με τα μαθήματα κάθε εξαμήνου
- [ ] Αυτόματη δημιουργία ενημερωμένου οδηγού σε μορφή PDF για κάθε αλλαγή στα πηγαία αρχεία με χρήση CI (π.χ., Travis-CI) και με οργάνωση δικτυακής υπηρεσίας
- [ ] Εναλλακτική ροή εργασίας και διαφορετικό σύστημα παραγωγής PDF, (πχ LaTeX), mobile app (π.χ., PWA)
- [ ] Τελική αναφορά σύμφωνα με τις οδηγίες στο κεντρικό αποθετήριο εργασιών
